language: java
branches:
  only:
    - master
before_install:
  - unset GEM_PATH
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
script: mvn clean install -Pqulice --quiet --batch-mode --errors
